# -*- coding: utf-8 -*-
"""ProjetoFinalchallenge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OYKldMny4gzjfiNs4E9PSm5DyFcQv7Ry
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -qU pypdf
# %pip install -U langchain
# %pip install -U langchain-community

!pip install -qU langchain-google-genai langchain
!pip install -qU langchain-community pypdf
!pip install gradio -q

# Busca as chaves do painel Secrets e insere nas variáveis de ambiente
import os
from google.colab import userdata

os.environ['GOOGLE_API_KEY'] = userdata.get('ChaveGemini')

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_community.document_loaders import PyPDFLoader

# Lista com todas as URLs dos PDFs da loja BimBam
urls = [
    'https://raw.githubusercontent.com/deboragborchardt/ProjetoFinal/main/GuiadePrazoseCustos.pdf',
    'https://raw.githubusercontent.com/deboragborchardt/ProjetoFinal/main/ManualdeGarantia.pdf',
    'https://raw.githubusercontent.com/deboragborchardt/ProjetoFinal/main/PerguntasFrequentes.pdf',
    'https://raw.githubusercontent.com/deboragborchardt/ProjetoFinal/main/PoliticaReembolsoDevolucao.pdf',
    'https://raw.githubusercontent.com/deboragborchardt/ProjetoFinal/main/ProgramadeAfiliados.pdf'
]

# Loop para carregar todas as páginas de todos os PDFs em uma variável só
textoDocumentos = ""

for url in urls:
    loader = PyPDFLoader(url)
    paginas = loader.load()
    for pagina in paginas:
        # Acumula o texto de cada página
        textoDocumentos += pagina.page_content + "\n\n"

def assistenteRespostas(pergunta):
    # Instancia o LLM do LangChain
    llm = ChatGoogleGenerativeAI(
        api_key=os.environ['GOOGLE_API_KEY'],
        model="gemini-2.5-flash"
    )

    # Monta o prompt
    prompt = f"""
Assuma que você é um atendente da loja BimBam Buy. Você deve responder as perguntas dos clientes com base nas informações dos documentos.
Responda de forma clara e objetiva.
Se a resposta não estiver nos documentos, diga "Não encontrei essa informação nos documentos."

DOCUMENTOS:
{textoDocumentos}

  INSTRUÇÕES:
    1. Responda de forma clara e objetiva
    2. Baseie sua resposta apenas nos documentos fornecidos
    3. Você tem informaçoes apenas sobre Guia de Prazos, Manual de Garantia, Perguntas Frequentes, Política de Rembolso e Programa de Afiliados.
    4. Voce nao consegue consultar pedidos especificos pelo chat
    6. Se a resposta não estiver nos documentos, diga "Não possuo essa informação."

PERGUNTA: {pergunta}
"""

    # Executa usando o método correto do LangChain (.invoke)
    response = llm.invoke(prompt)

    # Retorna o conteúdo da resposta (.content)
    return response.content

import gradio as gr

# Função que o Gradio vai chamar para cada mensagem enviada pelo usuário
def responder_chat(mensagem, historico):
    resposta = assistenteRespostas(mensagem)
    return resposta

# Criação da Interface HTML com Gradio (sem o parâmetro theme)
demo = gr.ChatInterface(
    fn=responder_chat,
    title="🛒 Atendimento BimBam Buy",
    description="Faça suas perguntas sobre nossos produtos, prazos, garantias e políticas!",
    textbox=gr.Textbox(placeholder="Digite sua pergunta aqui e pressione Enter...", container=False, scale=7)
)

# Inicia a interface na tela do Colab
#demo.launch(share=False)
demo.launch(share=True, debug=True)
